sudo: true
language: node_js
node_js:
  - "5.0"

cache:
  directories:
    - node_modules

install:
  - npm install --global lerna@2.0.0-beta.28
  - npm install
  - lerna bootstrap
  - npm run deploy:dev --package=tocco-ui-showcase

script:
  - npm run lint
  - npm run test

after_success:
  - npm run deploy:standalone --package=tocco-ui-showcase
  - bash deploy_showcase.sh

env:
  global:
  - ENCRYPTION_LABEL: "49dedc788d53"
  - COMMIT_AUTHOR_EMAIL: "bot@tocco.ch"
