sudo: true
language: node_js
node_js:
  - "5.0"

cache:
  directories:
    - node_modules
    - packages/tocco-ui/node_modules
    - packages/tocco-ui-showcase/node_modules
    - packages/tocco-ui-util/node_modules
    - packages/merge/node_modules
    - packages/login/node_modules

install:
  - npm install
  - lerna bootstrap

script:
  - npm run lint
  - npm run test

after_success:
  - npm run codecov
  - bash deployment/deploy_showcase.sh

env:
  global:
  - ENCRYPTION_LABEL: "49dedc788d53"
  - COMMIT_AUTHOR_EMAIL: "bot@tocco.ch"
